---
all:

  hosts:

    w-ubuntu:
      ansible_host: "10.0.0.34"
      ansible_user: "a-iakubov"
      encrypted_disk_partition: "/dev/sdb1"
      ansible_ssh_private_key_file: "/root/.ssh/id_rsa_w-ubuntu"
      passphrase_file: "/root/passphrase"

    remote-test-ubuntu:
      ansible_host: "3.124.x.x"
      ansible_user: "ubuntu"
      encrypted_disk_partition: "/dev/sdb1"
      passphrase_file: "/root/passphrase"

linux:
   hosts:
      w-ubuntu:
      remote-test-ubuntu:
