---
- name: Disable C-state for all CPUs
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=".*"'
    line: 'GRUB_CMDLINE_LINUX="usbcore.autosuspend=-1 processor.max_cstate=1"'
    backrefs: yes

- name: Update GRUB configurations
  command: "update-grub"
  notify: Restart server

#- name: Switch CPU operation mode
#  command: "cpupower frequency-set -g performance"
#  ignore_errors: yes

- name: Ensure that cpufrequtils config exists
  file:
    path: /etc/default/cpufrequtils
    state: touch
    mode: '0644'
    owner: root

- name: Enabling Performance governor in the cpufrequtils
  ansible.builtin.lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^GOVERNOR=".*"'
    line: 'GOVERNOR="performance"'
    state: present
  notify: Restart cpufrequtils

- name: Display CPU information and Hyper-Threading status
  command: "lscpu"
  register: lscpu_info

- name: Display CPU cores and Hyper-Threading status
  debug:
    var: lscpu_info.stdout_lines

- name: Display frequency info for the CPU
  command: cpufreq-info
  register: cpufreq_info

- name: Display CPU freqinfo
  debug:
    var: cpufreq_info.stdout_lines
